/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED_BLUE.h"
#include "LED_BLUE_aliases.h"
#include "SPIS.h"
#include "SPIS_SPI_UART.h"
#include "SPIS_PINS.h"
#include "SPIS_SPI_UART_PVT.h"
#include "SPIS_PVT.h"
#include "SPIS_BOOT.h"
#include "LED_GREEN.h"
#include "LED_GREEN_aliases.h"
#include "LED_RED.h"
#include "LED_RED_aliases.h"
#include "ADC_SAR_SEQ.h"
#include "RTD_RED.h"
#include "RTD_RED_aliases.h"
#include "Opamp_1.h"
#include "RTD_BLUE.h"
#include "RTD_BLUE_aliases.h"
#include "RTD.h"
#include "IDAC.h"
#include "IDC_Out.h"
#include "IDC_Out_aliases.h"
#include "OpAmp_Out.h"
#include "OpAmp_Out_aliases.h"
#include "CAL_100B.h"
#include "CAL_100B_aliases.h"
#include "CAL_100A.h"
#include "CAL_100A_aliases.h"
#include "switch_1.h"
#include "switch_1_aliases.h"
#include "RTD_RED_1.h"
#include "RTD_RED_1_aliases.h"
#include "CAL_100A_1.h"
#include "CAL_100A_1_aliases.h"
#include "FULL_RANGE_2.h"
#include "FULL_RANGE_2_aliases.h"
#include "FULL_RANGE_1.h"
#include "FULL_RANGE_1_aliases.h"
#include "OpAmp_In.h"
#include "OpAmp_In_aliases.h"
#include "SPIS_SCBCLK.h"
#include "SPIS_ss_s.h"
#include "SPIS_ss_s_aliases.h"
#include "SPIS_miso_s.h"
#include "SPIS_miso_s_aliases.h"
#include "SPIS_SCB_IRQ.h"
#include "SPIS_sclk_s.h"
#include "SPIS_sclk_s_aliases.h"
#include "SPIS_mosi_s.h"
#include "SPIS_mosi_s_aliases.h"
#include "ADC_SAR_SEQ_IRQ.h"
#include "ADC_SAR_SEQ_intClock.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

